### ISSUE TITLE
Frontend Masters lineman install issue

### ISSUE THREAD

**Issue by Nooshu** [testdouble/real-world-testing#4]
Hello,

I'm just following along on your course on FEM and I have just run into an issue. When doing an npm install from the lineman directory I get this nasty looking error

> png@3.0.3 install /Users/name/Development/tutorial-machine/build/js-testing/real-world-testing-video/lineman/node_modules/png
> node-gyp rebuild
> 
> /bin/sh: pkg-config: command not found
> gyp: Call to 'pkg-config libpng --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/Users/name/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Darwin 15.6.0
> gyp ERR! command "/Users/name/.nvm/versions/node/v6.5.0/bin/node" "/Users/name/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/name/Development/tutorial-machine/build/js-testing/real-world-testing-video/lineman/node_modules/png
> gyp ERR! node -v v6.5.0
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> npm WARN install:png@3.0.3 png@3.0.3 install: `node-gyp rebuild`
> npm WARN install:png@3.0.3 Exit status 1
> example@0.0.1 /Users/name/Development/tutorial-machine/build/js-testing/real-world-testing-video/lineman
> └── (empty)
> 
> npm ERR! code 1

Looking into the issue it looks like one of the PNG dependencies is broken, but after the issue was raised there's no fix https://github.com/pkrumins/node-png/issues/50.

Is this something you have come across or could verify if it is an issue for you too. I'm on OSX 10.11.6.

Great course by the way!

**Comment by searls** [comment]
First, thanks for the kind words about the course.

Second, yes I see this too:

```
> png@3.0.3 install /Users/justin/code/testdouble/real-world-testing/lineman/node_modules/png
> node-gyp rebuild

Package libpng was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpng.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpng' found
gyp: Call to 'pkg-config libpng --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/justin/.nodenv/versions/6.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/Users/justin/.nodenv/versions/6.3.0/bin/node" "/Users/justin/.nodenv/versions/6.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/justin/code/testdouble/real-world-testing/lineman/node_modules/png
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:png@3.0.3 png@3.0.3 install: `node-gyp rebuild`
npm WARN install:png@3.0.3 Exit status 1

> webdriver-http-sync@1.2.1 install /Users/justin/code/testdouble/real-world-testing/lineman/node_modules/webdriver-http-sync
> node-gyp rebuild

  CXX(target) Release/obj.target/curllib/curllib.o
  SOLINK_MODULE(target) Release/curllib.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
```

I don't really have a great answer for you 😦  -- @davemo, thoughts?

**Comment by dabisrat** [comment]
I was able to continue with the FEM course by globally installing lineman
